---
title: "R Notebook"
output: html_notebook
---

#1.0 Planejamento da solucao

Plotar gráfico de linha ao longo do tempo com as probabilidades do python



```{r}
library(tidyverse)

```



```{r}
data = read_csv("data_experiment.csv")
head(data)


```

```{r}
get_prob_and_loss <- function(data, sample_size = NULL) {
  
  vals <- list()
  prob_b_better_a <- c()
  expected_loss_a <- c()
  expected_loss_b <- c()
  
  for (day in 1:nrow(data)) {
    
    for (v in c("a", "b")) {
      
      # Generate Beta distribution params
      alpha <- 1 + data[day, paste0("acc_clicks_", toupper(v))]
            beta <- 1 + (data[day, paste0("acc_visits_", toupper(v))] - data[day, paste0("acc_clicks_", toupper(v))])
            
            vals[[paste0("u_", v)]] <- alpha / (alpha + beta)
            vals[[paste0("var_", v)]] <- (alpha * beta) / ((alpha + beta)^2 * (alpha + beta + 1))
      
      # Generate Normal distribution
      vals[[paste0("x_", v)]] <- rnorm(n = sample_size, mean = vals[[paste0("u_", v)]], sd = 1.25 * sqrt(vals[[paste0("var_", v)]]))
      
      # Generate Beta PDF
      vals[[paste0("f", v)]] <- dbeta(x = vals[[paste0("x_", v)]],
                                      shape1 = 1 + data[day, paste0("acc_clicks_", toupper(v))],
                                      shape2 = 1 + (data[day, paste0("acc_visits_", toupper(v))] - data[day, paste0("acc_clicks_", toupper(v))]))
      
      # Generate Normal PDF
      vals[[paste0("g", v)]] <- dnorm(x = vals[[paste0("x_", v)]],
                                      mean = vals[[paste0("u_", v)]],
                                      sd = 1.25 * sqrt(vals[[paste0("var_", v)]]))
    }
    
    # Beta / Normal
    y <- (vals[['fa']] * vals[['fb']]) / (vals[['ga']] * vals[['gb']])
    yb <- y[vals[['x_b']] >= vals[['x_a']]]
    
    # Calculate probabilities
    p <- (1 / sample_size) * sum(yb)
    
    expected_loss_A <- (1 / sample_size) * sum(((vals[["x_b"]] - vals[["x_a"]]) * y)[vals[["x_b"]] >= vals[["x_a"]]])
    expected_loss_B <- (1 / sample_size) * sum(((vals[["x_a"]] - vals[["x_b"]]) * y)[vals[["x_a"]] >= vals[["x_b"]]])
    
    prob_b_better_a <- c(prob_b_better_a, p)
    expected_loss_a <- c(expected_loss_a, expected_loss_A)
    expected_loss_b <- c(expected_loss_b, expected_loss_B)
  }
  
  return(list(prob_b_better_a, expected_loss_a, expected_loss_b))
}
```


```{r}
str(row.names(df1))
```
```{r}
select_if(df1, is.numeric) %>%  colnames
```
```{r}
select_if(df1, is.numeric) %>% colnames %>% droplevels()
```


```{r}
str(df1)
```


```{r}
df1[,!names(df1) %in% c("click", "visit")] %>% colnames
```
```{r}
select_if(df1, is.numeric) %>% colnames 
```



```{r}
df1 <- data
for (i in c('visit', 'click')) {
  df1[[i]] <- as.integer(df1[[i]])
}

df1$day <- row.names(df1) %>% as.integer()
df1 <- pivot_wider(df1, 
                   id_cols = day, 
                   names_from = group, 
                   names_glue = "{group}_{.value}",
                   values_from = c( "click", "visit", "no_click" ) , 
                   values_fn = sum )
df1[is.na(df1)] <- 0

for (i in colnames(df1)) {
  df1[[paste0("acc_", i)]] <- cumsum(df1[[i]])
}

df1 <- df1[,!names(df1) %in% c("acc_day")]

head(df1)

```

```{r}
pivot_wider
```


```{r}
str(df1)
```





```{r}
df1 <- data
for (i in c('visit', 'click')) {
  df1[[i]] <- as.integer(df1[[i]])
}
df1 <- df1 %>% 
  mutate(day = row_number()) %>% 
  pivot_wider(names_from = 'group', values_from = names(select_if(., is.numeric)), values_fn = sum) %>% 
  rename_all(~paste0("day_", .)) %>% 
  select(sort(names(.))) %>% 
  mutate_all(~replace_na(., 0)) %>% 
  rename_all(~sub("_", "", .)) %>% 
  mutate(across(everything(), cumsum)) %>% 
  rename(
    clicks_A = control_click,
    clicks_B = treatment_click,
    visits_A = control_visit,
    visits_B = treatment_visit,
    acc_clicks_A = acc_control_click,
    acc_clicks_B = acc_treatment_click,
    acc_visits_A = acc_control_visit,
    acc_visits_B = acc_treatment_visit
  )
```

```{r}
head(df1)
```



